config/routes.rb
Fakebook::Application.routes.draw do
  resources :mensagems

  root :to => 'home#index'
  get "home/index"

  authenticated :user do
	  resources :posts do
	  	resources :comments
	  	resources :post_likes do
		  	get :custom_create, 	on: :collection
		  	get	:custom_destroy, 	on: :member
		  end
	  end
	end
	
	resources :comments do
		resources :comment_likes do
	  	get :custom_create, 	on: :collection
	  	get	:custom_destroy, 	on: :member
	  end
	end
  
	resources :eventos do
		post :pesquisa, on: :collection
		resources :participacao_eventos
		member do
		  get :evento, :profile
		end
		match '/participar', :controller => 'eventos', :action => "participar"
	end
  
	resources :eventos do
		post :pesquisa, on: :collection
		resources :participacao_eventos
		match '/participacao_eventos/new', :controller => 'participacao_eventos', :action => 'new'
		member do
		  get :evento, :profile
		end
	end
  resources :participacao_eventos
  match '/eventos/index', :controller => 'eventos', :action => "index"
  
  
  

  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "users/omniauth_callbacks" } do
    resources :profiles  do
      member do
        get :following, :followers
        get :mural
      end
     
    end
     resources :relationships
  end

  match ':controller(/:action(/:id))(.:format)'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :comment_likes
  
  attr_accessible :body
  
  validates :body, :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@user = User.find(current_user) 
		@comment = Comment.create(params[:comment])
		@user.comments << @comment
		@post.comments << @comment
		# redirect_to post_path(@post)
		# redirect_to mural_posts_path
		
		respond_to do |format|
			format.js
		end
	end
	
	def destroy
	  @post = Post.find(params[:post_id])
	  @comment = @post.comments.find(params[:id])
	  @comment.destroy
	  # redirect_to post_path(@post)
	  #redirect_to mural_posts_path
		respond_to do |format|
			format.js
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
		<%= div_for comment, :class => 'comment' do %>
			<p><b><%= comment.user.profile.full_name %>:</b> <%= comment.body %></p>
			
			<div id="comment_like_<%= comment.id %>" class="_like">
			<% if not comment.comment_likes.empty? %>
				<% if comment.comment_likes.size == 1 %>
				<p><%= comment.comment_likes.first.user.profile.full_name %>  likes this.</p>
				<% else %>
				<p><%= comment.comment_likes.size %> people likes this.</p>
				<% end %>
			<% end %>
			</div>
						
			<% if comment.user == current_user || comment.post.user == current_user %>
			<%= link_to 'Destroy Comment', [comment.post, comment],
							:confirm => 'Are you sure?',
							:method => :delete, remote: true %> |
			<% end %>
			
			<% likes = comment.comment_likes.where(:user_id => current_user) %>
			<div id="comment_like_link_<%= comment.id %>" class="_like">
			<% if likes.size > 0 %>
				<%= link_to 'Unlike', custom_destroy_comment_comment_like_path(comment, likes.first), remote: true %>
			<% else %>
				<%= link_to 'Like', custom_create_comment_comment_likes_path(comment), remote: true %>
			<% end %>
			</div>

		<% end %>

app/views/comments/_comments.html.erb
	<% @post.comments.each do |comment| %>
		<p>
		  <b>Commenter:</b>
		  <%= comment.user.username %>
		</p>
	 
		<p>
		  <b>Comment:</b>
		  <%= comment.body %>
		</p>
		<% if comment.comment_likes.size > 0 %>
		<p>
			<%= comment.comment_likes.size %> people likes this.
		</p>
		<% end %>
		<p>
			<%= link_to 'Destroy Comment', [comment.post, comment],
							:confirm => 'Are you sure?',
							:method => :delete %> |
			<% likes = comment.comment_likes.where(:user_id => current_user) %>
			<% if likes.size > 0 %>
				<%= link_to 'Unlike', [comment, likes.first],
						:method => :delete %>
			<% else %>
		    <%= link_to 'Like', [comment, comment.comment_likes.build],
								:method => :create %>
			<% end %>
		</p>
	<% end %>

app/views/comments/_comments_mural.html.erb
	<% post.comments.each do |comment| %>
		<p style="text-weight: bold;">
		  <%= comment.user.username %>
		</p>
	 
		<p>
		  <%= comment.body %>
		</p>
		<% if comment.comment_likes.size > 0 %>
		<p>
			<%= comment.comment_likes.size %> people likes this.
		</p>
		<% end %>
		<p>
			<% if comment.user = current_user || post.user = current_user %>
			<%= link_to 'Destroy Comment', [comment.post, comment],
							:confirm => 'Are you sure?',
							:method => :delete %> |
			<% end %>
			<% likes = comment.comment_likes.where(:user_id => current_user) %>
			<% if likes.size > 0 %>
				<%= link_to 'Unlike', [comment, likes.first],
						:method => :delete %>
			<% else %>
		    <%= link_to 'Like', [comment, comment.comment_likes.build],
								:method => :create %>
			<% end %>
		</p>
	<% end %>

app/views/comments/_form.html.erb
	<%= form_for([@post, @post.comments.build]) do |f| %>
		<div class="field">
		  <%= f.label :body %><br />
		  <%= f.text_area :body %>
		</div>
		<div class="actions">
		  <%= f.submit %>
		</div>
	<% end %>
	 
	<%= link_to 'Edit Post', edit_post_path(@post) %> |
	<%= link_to 'Back to Posts', posts_path %>

app/views/comments/_form_mural.html.erb
	<%= form_for([post, post.comments.build]) do |f| %>
		<div class="field">
		  <%= f.label :body %><br />
		  <%= f.text_field :body %>
		</div>
		<div class="actions">
		  <%= f.submit %>
		</div>
	<% end %>

app/views/comments/create.js.erb
$('div#comments_<%= @comment.post.id %>').append("<%= escape_javascript(render @comment) %>");
$('div#comments_<%= @comment.post.id %>').fadeIn();
$('div#form_comment_<%= @comment.post.id %> input#comment_body').val('');
$('div#form_comment_<%= @comment.post.id %> input#comment_body').focus();

app/views/comments/destroy.js.erb
$('#<%= dom_id(@comment) %>').fadeOut();