config/routes.rb
Fakebook::Application.routes.draw do
  resources :mensagems

  root :to => 'home#index'
  get "home/index"

  authenticated :user do
	  resources :posts do
	  	resources :comments
	  	resources :post_likes do
		  	get :custom_create, 	on: :collection
		  	get	:custom_destroy, 	on: :member
		  end
	  end
	end
	
	resources :comments do
		resources :comment_likes do
	  	get :custom_create, 	on: :collection
	  	get	:custom_destroy, 	on: :member
	  end
	end
  
	resources :eventos do
		post :pesquisa, on: :collection
		resources :participacao_eventos
		member do
		  get :evento, :profile
		end
		match '/participar', :controller => 'eventos', :action => "participar"
	end
  
	resources :eventos do
		post :pesquisa, on: :collection
		resources :participacao_eventos
		match '/participacao_eventos/new', :controller => 'participacao_eventos', :action => 'new'
		member do
		  get :evento, :profile
		end
	end
  resources :participacao_eventos
  match '/eventos/index', :controller => 'eventos', :action => "index"
  
  
  

  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "users/omniauth_callbacks" } do
    resources :profiles  do
      member do
        get :following, :followers
        get :mural
      end
     
    end
     resources :relationships
  end

  match ':controller(/:action(/:id))(.:format)'
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :profile
  has_many :participacao_eventos, foreign_key:"evento_id"
  
 

  has_many :profiles, through: :participacao_eventos
  attr_accessible :nome, :data, :local, :criador, :desc
  validates_presence_of :nome, :local, :message => "esta em branco"
  validates_uniqueness_of :nome, :message => "ja existe"   
  
  
  
  
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController

before_filter do
  authenticate_user! rescue redirect_to auth_url
end  

  def index
    @search = Search.new(:evento, params[:search])

	@eventos = current_user.profile.eventos
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos }
    end
  end

  def pesquisa
    @search = Search.new(:evento, params[:search])
    @eventos = @search.run(:order => 'data')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos }
    end
  end
  
  def show2
    @evento = Evento.find(params[:id])
  end
  
  def participar
   
  end
 
  
  def show
    @evento = Evento.find(params[:id])
  end

  def new
    @evento = Evento.new
  end

  def create
#    @evento = Evento.new(params[:evento])
    @profile = current_user.profile
    @evento = @profile.eventos.build(params[:evento])

    if @evento.save
      redirect_to @evento, :notice => "Evento criado com sucesso."
    else
      render :action => 'new'
    end
  end

  def edit
    @evento = Evento.find(params[:id])
  end

  def update
    @evento = Evento.find(params[:id])
    if @evento.update_attributes(params[:evento])
      redirect_to @evento, :notice  => "Evento atualizado com sucesso."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy
    redirect_to eventos_url, :notice => "Evento excluido com sucesso."
  end
end

app/views/eventos/_form.html.erb
<%= form_for @evento do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :data %><br />
    <%= f.datetime_select :data, :order => [:day, :month, :year]  %>
  </p>
  <p>
    <%= f.label :local %><br />
    <%= f.text_field :local %>
  </p>
    <p>
    <%= f.label :criador %><br />
    <%= f.text_field :criador %>
  </p>
  <p>
    <%= f.label :descrição %><br />
    <%= f.text_area :desc , :rows => 5, :cols => 32, :maxlength => 150 %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/eventos/edit.html.erb
<% title "Edit Data" %>

<%= render 'form' %>

<p>
  <%= link_to "View", @evento %> |
  <%= link_to "Back", eventos_path %>
</p>

app/views/eventos/index.html.erb
<% title "Events" %>
<% @profile_id = current_user.profile.id %>
<p><%= link_to "Create your Event", new_evento_path %></p>
<%= form_for @search, :url => "/eventos/pesquisa" do |f| %>
<table> 
  <tr>
     <td>Name:</td>  
     <td>Local:</td>
     <td>Owner:</td>
  </tr> 
  <tr>
     <td><% String campo = 'nome' %>
        <%= f.text_field campo, size:20 %></td> 
     <td><%= f.text_field 'local', size:20 %></td> 
     <td><%= f.text_field 'criador', size:20 %></td>      
     <td><%= f.submit "Search" %></td>
  </tr>
 </table> 
<% end %>

<br/> 
<hr/>
<h3>My Events</h3>
<table>
   <% for evento in @eventos %>
	  <p>
	  <tr><td><strong>Name:</strong></td><td><%= evento.nome %></td></tr>
	  <tr><td><strong>Date:</strong> </td><td><%= evento.data.strftime('%d %b %Y') %><div id="spc"><div/></td>
	  <td>&#32;&#32;<%= link_to "View", evento %></td>
	  <% unless evento.profile_id != @profile_id %>
		<td><%= link_to "Edit", edit_evento_path(evento) %></td>
		<td>&#32;&#32;<%= link_to "Delete", evento, :confirm => 'are you sure?', :method => :delete %></td></tr>
	  <% else %>
		<td>&#32;&#32;<%= link_to "Join", evento_participar_path(evento), :confirm => 'are you sure?' %></td></tr>
	  <% end %>
	  <tr><td><strong>Local:</strong></td><td><%= evento.local %>   </td></tr>
	  <tr><td><div id="spc2"><div/><td> </tr>
	  </p>
    <% end %>
    <%= paginate @eventos %>
</table>

<% @participacoes = current_user.profile.participations %>
<h3>Confirmed Events Participations</h3>
<table>
	<% for participacao in @participacoes %>
		<p>
		<tr><td><strong>Name:</strong></td><td><%= participacao.nome %></td></tr>
		<tr><td><strong>Date:</strong> </td><td><%= participacao.data.strftime('%d %b %Y') %><div id="spc"><div/></td>
		<td>&#32;&#32;<%= link_to "View", participacao %></td>
		<tr><td><strong>Local:</strong></td><td><%= participacao.local %>   </td></tr>
		<tr><td><div id="spc2"><div/><td> </tr>
	  </p>
    <% end %>
	<%= paginate @participacoes %>
</table>
<p><%= link_to "Back", home_index_path%></p>

app/views/eventos/new.html.erb
<% title "Criate Event" %>

<%= render 'form' %>

<p><%= link_to "Back", eventos_path %></p>

app/views/eventos/pesquisa.html.erb
<% title "Events" %>
<% @profile_id = current_user.profile.id %>
<p><%= link_to "Criate your Event", new_evento_path %></p>
<%= form_for @search, :url => "/eventos/pesquisa" do |f| %>
<table> 
  <tr>
     <td>Name:</td>  
     <td>Local:</td>
     <td>Owner:</td>
  </tr> 
  <tr>
     <td><% String campo = 'nome' %>
        <%= f.text_field campo, size:20 %></td> 
     <td><%= f.text_field 'local', size:20 %></td> 
     <td><%= f.text_field 'criador', size:20 %></td>      
     <td><%= f.submit "Search" %></td>
  </tr>
 </table> 
<% end %>

<br/> 
<hr/>
<table>
   <% @eventos.each do|evento| %>
	  <% @participacoes = evento.participacao_eventos %>
	  <p>
	  <tr><td><strong>Name:</strong></td><td><%= evento.nome %></td></tr>
	  <tr><td><strong>Date:</strong> </td><td><%= evento.data.strftime('%d %b %Y') %>
	  <div id="spc"><div/></td><td>&#32;&#32;<%= link_to "View", evento %></td><td>
	  <% unless evento.profile_id != @profile_id %>
		<%= link_to "Edit", edit_evento_path(evento) %>
		<%= link_to "Delete", @evento, :confirm => 'Are you sure?', :method => :delete %>
	  <% else %>
		<% unless @participacoes.find(:first, :conditions => ["profile_id = ?", @profile_id]) %>
			<%= link_to "Join", evento_participacao_eventos_new_path(evento) %></td></tr>
		<% end %>
	  <% end %>
	  <tr><td><strong>Local:</strong></td><td><%= evento.local %></td></tr>
	  <tr><td><div id="spc2"><div/><td> </tr>
	  </p>
    <% end %>
</table>
<p><%= link_to "Back", home_index_path%></p>

app/views/eventos/show.html.erb
<% title   @evento.nome  %>
<% @profile_id = current_user.profile.id %>
<% @participations = @evento.participacao_eventos %>
<div id="lateral">

    <div id= "image">
      <center>
       <%= image_tag("eventos.png", :alt=>"ok", :size=> "180x180")%>
      </center>
    </div>
  </br>
    <p>
      <strong>Participantes:</strong>
<% @participantes = @evento.profiles %>
<table>
<% for participante in @participantes %>
	<tr><td><%= participante.full_name %></td></tr>
<% end %>
</table>
    </p>

<p>

</p>
</div><div id="conteudo">
  
<p>
  <strong>Date:</strong>
  <%= @evento.data.strftime('%d %b %Y') %>

</p>
<p>
  <strong>Hour:</strong>
    <%= @evento.data.strftime('%Hh') %>
    
    <%= @evento.data.strftime('%M') %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @evento.criador %>
</p>

<p>
  <strong>Local:</strong>
  <%= @evento.local %>
</p>
<p>
  <strong>Description:</strong>
  <%= @evento.desc %>
</p>
  <% unless @evento.profile_id != @profile_id %>
	<%= link_to "Edit", edit_evento_path(@evento) %> |
	<%= link_to "Delete", @evento, :confirm => 'Are you sure?', :method => :delete %> |
  <% else %>
<% unless @participations.find(:first, :conditions => ["profile_id = ?", @profile_id]) %>
			<%= link_to "Join", evento_participacao_eventos_new_path(@evento) %></td></tr>
		<% end %>
  <% end %>
  <%= link_to "Back", eventos_path %>
 <br>
 <br/>
  <br>
 <br/>
  
</div>

app/views/eventos/show2.html.erb
<% title   @evento.nome  %>

<div id="lateral">

    <div id= "image">
      <center>
       <%= image_tag("eventos.png", :alt=>"ok", :size=> "180x180")%>
      </center>
    </div>
  </br>
    <p>
      <strong>Participantes:</strong>
    </p>

<p>

</p>
</div><div id="conteudo">
  
<p>
  <strong>Data:</strong>
  <%= @evento.data.strftime('%d %b %Y') %>

</p>
<p>
  <strong>Horario:</strong>
    <%= @evento.data.strftime('%Hh') %>
    
    <%= @evento.data.strftime('%M') %>
</p>
<p>
  <strong>Criador:</strong>
  <%= @evento.criador %>
</p>


<p>
  <strong>Local:</strong>
  <%= @evento.local %>
</p>
<p>
  <strong>Descrição:</strong>
  <%= @evento.desc %>
</p>
  
  
</div>
  <%= link_to "Participar", @evento, :confirm => 'Deseja Participar?', :method => :participar %> |
  <%= link_to "Voltar", eventos_path %>