config/routes.rb
Fakebook::Application.routes.draw do
  resources :mensagems

  root :to => 'home#index'
  get "home/index"

  authenticated :user do
	  resources :posts do
	  	resources :comments
	  	resources :post_likes do
		  	get :custom_create, 	on: :collection
		  	get	:custom_destroy, 	on: :member
		  end
	  end
	end
	
	resources :comments do
		resources :comment_likes do
	  	get :custom_create, 	on: :collection
	  	get	:custom_destroy, 	on: :member
	  end
	end
  
	resources :eventos do
		post :pesquisa, on: :collection
		resources :participacao_eventos
		member do
		  get :evento, :profile
		end
		match '/participar', :controller => 'eventos', :action => "participar"
	end
  
	resources :eventos do
		post :pesquisa, on: :collection
		resources :participacao_eventos
		match '/participacao_eventos/new', :controller => 'participacao_eventos', :action => 'new'
		member do
		  get :evento, :profile
		end
	end
  resources :participacao_eventos
  match '/eventos/index', :controller => 'eventos', :action => "index"
  
  
  

  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "users/omniauth_callbacks" } do
    resources :profiles  do
      member do
        get :following, :followers
        get :mural
      end
     
    end
     resources :relationships
  end

  match ':controller(/:action(/:id))(.:format)'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :post_likes
  
  attr_accessible :content
  
  validates :content, :presence => true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!
	
  # GET /posts
  # GET /posts.json
  def index
  	@user = User.find(current_user)
    # @posts = Post.all
    @posts = @user.posts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
  	@user = User.find(current_user)
    # @post = Post.new(params[:post])
    @post = @user.posts.create(params[:post])

    respond_to do |format|
      if @post.save
        format.html # { redirect_to mural_posts_path, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html #{ redirect_to mural_posts_path }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% new_post = Post.new %>
<%= form_for(new_post, remote: true) do |f| %>
  <% if new_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(new_post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% new_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b>New post:</b><br />
    <%= f.text_field :content, :class => "text_field_mural" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/posts/_post.html.erb
	<%= div_for post do %>
		<p>
			<b><%= post.user.profile.full_name %>:</b><br />
			<!-- tratamento do conteudo -->
			<% content = post.content %>
			<% uris = URI.extract(content) %>

			<% uris.each do |uri| %>
				<% content.gsub!(uri, 
					'<a href="' + uri + '" target="_blank">' + uri + '</a>') %>
			<% end %>
			
			<%= content.html_safe %><br />
			
			<% 
				if not uris.empty? then # existem uris
					uri = uris.first
					require 'mechanize'
					agent = Mechanize.new
					uri_split = uri.split('?')
					
					# tratamento de erro ao requisitar página
					begin

						if uri_split.size > 1 then
							params = uri_split[1].split('&')
							uri_obj 	= agent.get(uri_split[0], params)
						else
							uri_obj 	= agent.get(uri_split[0])
						end
						uri_class	= uri_obj.class
				 	
				 		if uri_class == Mechanize::Image then %>
							<!-- imagem -->
							<%= image_tag uri %>
							<!-- fim imagem -->
			<% 		else # não é imagem 
							if uri_class == Mechanize::Page then  %>
							<% if not uri_split[0].index("youtube.com").nil? and params.size > 0 %>
								<!-- video -->
								<% require 'youtube_it' %>
								<% client = YouTubeIt::Client.new %>
								<% video = client.video_by(uri) %>
							
								<div id="video_player_<%= post.id %>" style="display: none;">
								<%= video.embed_html(width = 325, height = 250).html_safe %>
								</div>
								<div id="link_description_<%= post.id %>" class="link_description">
									<div id="link_thumbnail_<%= post.id %>" class="link_thumbnail">
										<img src="<%= image_path 'play-icon-thumbnail.png' %>" id="video_play_button_<%= post.id %>" class="video_play_icon" data="<%= post.id %>" />
										<%= image_tag video.thumbnails[0].url, :class => 'link_image' %>
									</div>
									<div style="display: inline; position: relative;">
										<p>
											<a href="<%= uri %>"><%= uri_obj.title %></a><br />
											<span class="link_host"><%= URI(uri).host %>
										</p>
									</div>
								</div>
								<!-- fim video -->
							<% else %>
								<!-- pagina comum -->
								<div id="link_description_<%= post.id %>" class="link_description">
									<div style="display: inline; position: relative;">
									<p>
										<a href="<%= uri %>"><%= uri_obj.title %></a><br />
										<span class="link_host"><%= URI(uri).host %>
									</p>
									</div>
								</div>
								<!-- fim pagina comum -->
							<% end %>
			<%
							end
						end	# fim não é imagem

					rescue
			%>
					<div id="link_description_<%= post.id %>" class="link_description">
						<div style="display: inline; position: relative;">
						<p style="padding: 0px; margin: 5px; text-align: center;">
							<img src="<%= image_path 'loading.gif' %>" /><br />
							LOADING
						</p>
						</div>
					</div>
			<%
					end
					# fim tratamento
						
				end # fim existem uris
			%>

			<!-- fim tratamento do conteudo -->
		</p>
		
		<div id="post_like_<%= post.id %>" class="_like">
		<% if post.post_likes.size > 0 %>
			<% if post.post_likes.size == 1 %>
			<p><%= post.post_likes.first.user.profile.full_name %>  likes this.</p>
			<% else %>
			<p><%= post.post_likes.size %> people likes this.</p>
			<% end %>
		<% end %>
		</div>
		
		<% if post.user == current_user %>
			<%= link_to 'Destroy post', post, confirm: 'Are you sure?', 
				method: :delete, remote: true %> | 
		<% end %>
		
		<div id="post_like_link_<%= post.id %>" class="_like">
		<% likes = post.post_likes.where(:user_id => current_user) %>
		<% if likes.size > 0 %>
			<%= link_to 'Unlike', custom_destroy_post_post_like_path(post, likes.first),
					remote: true %>
		<% else %>
			<%= link_to 'Like', custom_create_post_post_likes_path(post), remote: true %>
		<% end %>
		</div>
		
		<!-- comentarios -->
		<p style="font-weight: bold;">Comments</p>
		<div id="comments_<%= post.id %>">
		<% post.comments.each do |comment| %>
			<%= render comment %>
		<% end %>
		</div>
		<!-- fim comentarios -->
			
		<!-- formulario comentario -->
		<div id="form_comment_<%= post.id %>">
		<p style="font-weight: bold;">Add a comment:</p>
		<%= form_for([post, post.comments.build], remote: :true) do |f| %>
			<div class="field">
				<%= f.text_field :body, :class => "text_field_mural" %>
			</div>
			<div class="actions">
				<%= f.submit %>
			</div>
		<% end %>
		</div>
		<!-- fim formulario comentario -->
		
		<hr class="linha_mural" />
	<% end %>
	
	

app/views/posts/create.js.erb
$('div#posts').prepend("<%= escape_javascript(render @post) %>");
$('div#<%= dom_id(@post) %>').fadeIn();
$('input#post_content').val('');
$('input#post_content').focus();

$('div.link_description div.link_thumbnail img.video_play_icon').click(function(event) { 
	event.preventDefault();
	id = $(this).attr('data');
	$('div#link_description_' + id).fadeOut();
	$('div#video_player_' + id).fadeIn();
});

app/views/posts/destroy.js.erb
$('#<%= dom_id(@post) %>').fadeOut();

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <td><%= post.user.username %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/mural.html.erb
	<p id="notice"><%= notice %></p>
	<%= render 'form' %>
	<hr class="linha_mural" />
	<div id="posts">
		<%= render @posts %>
	</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>User:</b>
  <%= @post.user.username %>
</p>
<% if @post.post_likes.size > 0 %>
<p>
	<%= @post.post_likes.size %> people likes this.
</p>
<% end %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %> |
<%= link_to 'Destroy Post', @post, confirm: 'Are you sure?', method: :delete %> | 
<% likes = @post.post_likes.where(:user_id => current_user) %>
<% if likes.size > 0 %>
	<%= link_to 'Unlike', [@post, likes.first],
			:method => :delete %>
<% else %>
	<%= link_to 'Like', [@post, @post.post_likes.build],
			:method => :create %>
<% end %>
<h2>Comments</h2>
<%= render :partial => "comments/comments" %>

<h2>Add a comment:</h2>
<%= render :partial => "comments/form" %>